services:
  - name: fastapi-app
    type: web
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CELERY_BROKER_URL
        value: redis://redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://redis:6379/0
    # ports:
    #   - port: 8000
    buildCommand: docker build -t fastapi-app .
    # startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # dependsOn:
    #   - redis

  - name: celery-worker
    type: worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CELERY_BROKER_URL
        value: redis://redis:6379/0
      - key: CELERY_RESULT_BACKEND
        value: redis://redis:6379/0
    buildCommand: docker build -t celery-worker .
    # startCommand: celery -A app.tasks worker --loglevel=info
    # dependsOn:
    #   - redis

  - name: redis
    type: redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
      description: everywhere